name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - run: |
        curl https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > sbt && chmod +x sbt
        ./sbt +test
